---
- name: ensure git is installed
  apt: pkg=git-core state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}

- name: ensure required apt packages are installed
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time={{ apt_cache_valid_time }}
  with_items: rails_deploy_apt_packages_required